baseURL = 'http://danielmartinezolivas.com/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Daniel Martinez'
copyright = "This is a customized copyright."
theme = "diary"
# favicon = "Your Favicon Address"
# cloudflareToken = "your cloudflare web analytics token"
# googleAnalytics = "UA-123-45"
# googleSiteVerification = "xxxx-xxxx"
# googleSearchCode = "Your Search Code"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/about"
name = "About"
weight = 4

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Posts"
weight = 1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
    subtitle = "Personal Website."
    enableGitalk = false
    disableToC = false

[params.gitalk]
    owner = "user"
    repo = "repo name"
    client_id = "your client id"
    client_secret = "your client secret"

[params.utterances]
    repo="your repo"
    term="[ENTER TERM HERE]"
    label="your label"
    theme="github-light"
